language: node_js
node_js: "4"

sudo: required
dist: trusty
branches:
  only:
    - master

install:
  # fetch the latest commit of submodules
  - git submodule update --remote
  - sudo apt-get -y install pandoc
  - npm install hexo gulp -g
  - npm install

script:
  - hexo generate
  - gulp

after_success:
  - git config --global user.name "Dongdong Tian"
  - git config --global user.email "seisman.info@gmail.com"
  - sed -i "s~git@github.com:~https://${GH_TOKEN}@github.com/~" _config.yml
  - hexo deploy
