language: node_js
node_js: "4"

sudo: required
dist: trusty
branches:
  only:
    - master

cache:
  directories:
    - node_modules

install:
  # fetch the latest commit of submodules
  - git submodule update --remote
  # install the latest version of pandoc
  - curl -s https://api.github.com/repos/jgm/pandoc/releases/latest | grep 'browser_download_url.*deb' | awk '{print "wget", $2}' | sh
  - sudo dpkg -i pandoc-*-amd64.deb
  - npm install hexo gulp -g
  - npm install

script:
  - hexo generate --silent
  - gulp

after_success:
  - git config --global user.name "Dongdong Tian"
  - git config --global user.email "seisman.info@gmail.com"
  - sed -i "s~git@github.com:~https://${GH_TOKEN}@github.com/~" _config.yml
  - hexo d
